name: GHCR Cleanup

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  workflow_dispatch:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Delete versions older than 1 year
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: docker-cloudflared
          older-than: 1 year
          keep-n-tagged: 3     # Safety: always keep the 5 newest tagged versions
          delete-untagged: false # Clean up those "unknown/unknown" entries
          dry-run: true  
